spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password:
  sql:
    init:
      mode: always  # auto-run schema.sql/data.sql in dev

app:
  db:
    vendor: h2
    host: localhost
    port: 9092
    name: devdb
    user: sa
    password: ""
